BEGIN;

DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS score_events;
DROP TABLE IF EXISTS predictions;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS room_invites;
DROP TABLE IF EXISTS room_members;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS auth_accounts;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

COMMIT;
